<?php

/**
 * @file
 * Install, update and uninstall hooks for the Demo1 install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function demo1_install() {
  // First, do everything that is done in the standard profile.
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();

  // Add code here to make nodes, terms, etc.
}
